server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    name: internalDB
    password: ''
    generate-unique-name: false
    username: sa
    url: jdbc:h2:~/school
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
